from __future__ import annotations

from typing import Any, Iterable, Protocol
from uuid import UUID

from app.schemas import CaseSpec, Report, ReviewQueueItem, ScoreResult, Session, TaskFamily
from app.schemas.contracts import Rubric
from app.schemas.contracts import EventItem


class CaseRepository(Protocol):
    def save_case(self, case: CaseSpec) -> CaseSpec: ...

    def get_case(self, case_id: UUID) -> CaseSpec | None: ...

    def list_cases(self, tenant_id: str) -> list[CaseSpec]: ...

    def save_task_family(self, task_family: TaskFamily) -> TaskFamily: ...

    def get_task_family(self, task_family_id: UUID) -> TaskFamily | None: ...

    def list_task_families(self, tenant_id: str) -> list[TaskFamily]: ...

    def save_rubric(self, rubric: Rubric) -> Rubric: ...

    def get_rubric(self, rubric_id: UUID) -> Rubric | None: ...

    def tenant_for_task_family(self, task_family_id: UUID) -> str | None: ...

    def case_for_task_family(self, task_family_id: UUID) -> CaseSpec | None: ...


class SessionRepository(Protocol):
    def save_session(self, session: Session) -> Session: ...

    def get_session(self, session_id: UUID) -> Session | None: ...

    def list_sessions(self, tenant_id: str) -> list[Session]: ...

    def append_events(self, session_id: UUID, events: Iterable[EventItem | dict[str, Any]]) -> int: ...

    def list_events(self, session_id: UUID) -> list[dict[str, Any]]: ...


class ScoringRepository(Protocol):
    def save_score(self, score: ScoreResult) -> ScoreResult: ...

    def get_score(self, session_id: UUID) -> ScoreResult | None: ...

    def save_report(self, report: Report) -> Report: ...

    def get_report(self, session_id: UUID) -> Report | None: ...

    def save_review_item(self, item: ReviewQueueItem) -> ReviewQueueItem: ...

    def get_review_item(self, session_id: UUID) -> ReviewQueueItem | None: ...

    def save_export_run(self, run_id: UUID, session_id: UUID) -> dict[str, str]: ...

    def get_export_run(self, run_id: UUID) -> dict[str, str] | None: ...
